# Generated by Django 4.2 on 2023-04-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField()),
                ('seller_name', models.CharField(max_length=50)),
                ('seller_address', models.CharField(default='', max_length=150)),
                ('seller_phone', models.CharField(default='', max_length=50)),
                ('buyer_name', models.CharField(max_length=50)),
                ('buyer_address', models.CharField(default='', max_length=150)),
                ('buyer_phone', models.CharField(default='', max_length=50)),
                ('totalproducts', models.IntegerField(default=0)),
            ],
        ),
    ]
