# Generated by Django 4.2 on 2023-04-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0003_remove_invoice_invoice_num_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='totalproducts',
            field=models.IntegerField(default=1),
        ),
    ]
