# Generated by Django 4.2 on 2023-04-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0004_alter_invoice_totalproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_id',
            field=models.IntegerField(default=1),
        ),
    ]
