# Generated by Django 4.2 on 2023-04-20 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0005_invoice_invoice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_id',
        ),
    ]
