# Generated by Django 4.2 on 2023-04-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0006_remove_invoice_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_id',
            field=models.IntegerField(default=1),
        ),
    ]
