# Generated by Django 4.2 on 2023-04-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0010_remove_invoice_id_invoice_invoice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=200)),
                ('total', models.CharField(max_length=10)),
            ],
        ),
    ]
