# Generated by Django 4.2 on 2023-04-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0011_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
